import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.DATABASE_URL);

const questions = [
  // ---- AYT MATEMATİK (16 soru) ----
  { cat: 'ayt-matematik', sub: 'matematik', q: '$f(x) = x^3 - 6x^2 + 9x + 1$ fonksiyonunun yerel minimum değeri kaçtır?', o: ['A) 1', 'B) 3', 'C) 5', 'D) 7', 'E) 9'], c: 0, e: "$f'(x)=3x^2-12x+9=3(x-1)(x-3)$. f''(3)=6>0 (min). f(3)=1." },
  { cat: 'ayt-matematik', sub: 'matematik', q: '$\\lim_{x \\to 2} \\frac{x^2 - 4}{x - 2}$ limitinin değeri kaçtır?', o: ['A) 0', 'B) 1', 'C) 2', 'D) 3', 'E) 4'], c: 3, e: '$\\frac{(x-2)(x+2)}{x-2} = x+2$. Limit: 2+2=4.' },
  { cat: 'ayt-matematik', sub: 'matematik', q: '$\\int (3x^2 - 4x + 2)dx$ integralinin sonucu nedir?', o: ['A) $x^3 - 2x^2 + 2x + C$', 'B) $x^3 - 4x^2 + 2x + C$', 'C) $3x^3 - 4x^2 + x + C$', 'D) $x^3 - 4x^2 + x + C$', 'E) $3x^3 - 2x^2 + 2x + C$'], c: 0, e: '$\\int 3x^2 = x^3$, $\\int -4x = -2x^2$, $\\int 2 = 2x$.' },
  { cat: 'ayt-matematik', sub: 'matematik', q: '$\\log_2(x-1) + \\log_2(x+1) = 3$ denkleminin çözümü kaçtır?', o: ['A) 2', 'B) 3', 'C) 4', 'D) 5', 'E) 6'], c: 1, e: '$\\log_2(x^2-1)=3 \\implies x^2-1=8 \\implies x^2=9 \\implies x=3$ (x>1).' },
  { cat: 'ayt-matematik', sub: 'matematik', q: 'İlk terimi 3, ortak farkı 5 olan aritmetik dizinin 12. terimi kaçtır?', o: ['A) 53', 'B) 55', 'C) 57', 'D) 58', 'E) 60'], c: 3, e: '$a_{12} = 3 + (12-1) \\times 5 = 3 + 55 = 58$.' },
  { cat: 'ayt-matematik', sub: 'matematik', q: '$\\int_{0}^{1} (x^2 + 1) dx$ integralinin değeri kaçtır?', o: ['A) $\\frac{2}{3}$', 'B) $\\frac{4}{3}$', 'C) $\\frac{5}{3}$', 'D) $\\frac{7}{3}$', 'E) $\\frac{8}{3}$'], c: 1, e: '$[\\frac{x^3}{3} + x]_0^1 = \\frac{1}{3} + 1 = \\frac{4}{3}$.' },
  { cat: 'ayt-matematik', sub: 'matematik', q: '$\\sin^2 x + \\cos^2 x$ ifadesinin değeri nedir?', o: ['A) -1', 'B) 0', 'C) $\\frac{1}{2}$', 'D) 1', 'E) 2'], c: 3, e: 'Temel trigonometrik özdeşlik: $\\sin^2 x + \\cos^2 x = 1$.' },
  { cat: 'ayt-matematik', sub: 'matematik', q: '$P(x)=2x^3-3x^2+4x-1$ polinomunun $x-2$ ile bölümünden kalan kaçtır?', o: ['A) 9', 'B) 11', 'C) 13', 'D) 15', 'E) 17'], c: 1, e: '$P(2) = 16 - 12 + 8 - 1 = 11$.' },
  { cat: 'ayt-matematik', sub: 'geometri', q: 'Dik kenarları 5 ve 12 cm olan dik üçgenin hipotenüsü kaç cm\'dir?', o: ['A) 10', 'B) 11', 'C) 12', 'D) 13', 'E) 14'], c: 3, e: '$c = \\sqrt{5^2 + 12^2} = \\sqrt{169} = 13$.' },
  { cat: 'ayt-matematik', sub: 'geometri', q: 'Taban yarıçapı 4 cm, ana doğrusu 10 cm olan koninin yanal alanı kaç $\\pi$ cm²\'dir?', o: ['A) 20', 'B) 30', 'C) 40', 'D) 50', 'E) 60'], c: 2, e: 'Yanal alan: $\\pi r l = \\pi \\times 4 \\times 10 = 40\\pi$.' },
  { cat: 'ayt-matematik', sub: 'geometri', q: 'Köşegeni $8\\sqrt{2}$ cm olan karenin çevresi kaç cm\'dir?', o: ['A) 16', 'B) 24', 'C) 28', 'D) 30', 'E) 32'], c: 4, e: '$a\\sqrt{2}=8\\sqrt{2} \\implies a=8$. Çevre: $4 \\times 8 = 32$.' },
  { cat: 'ayt-matematik', sub: 'geometri', q: 'Küre alanı $36\\pi$ cm² ise hacmi kaç $\\pi$ cm³\'tür?', o: ['A) 18', 'B) 27', 'C) 36', 'D) 48', 'E) 54'], c: 2, e: '$4\\pi r^2=36\\pi \\implies r=3$. $V=\\frac{4}{3}\\pi r^3 = 36\\pi$.' },
  // ---- AYT FEN (16 soru) ----
  { cat: 'ayt-fen', sub: 'fizik', q: 'Fotoelektrik olayda ışığın frekansı artırılırsa hangisi kesinlikle doğrudur? I. Maksimum kinetik enerji artar. II. Sökülme süresi kısalır. III. Akımın maksimum değeri artar.', o: ['A) Yalnız I', 'B) Yalnız II', 'C) I ve II', 'D) I ve III', 'E) I, II ve III'], c: 0, e: '$E_k = hf - \\phi$ olduğundan I doğru. Sökülme süresi anlıktır, akım şiddete bağlıdır.' },
  { cat: 'ayt-fen', sub: 'fizik', q: 'Yay sabiti 400 N/m olan yay 10 N ile sıkıştırılırsa depolanan enerji kaç J\'dür?', o: ['A) 0.125', 'B) 0.25', 'C) 0.5', 'D) 1', 'E) 2'], c: 0, e: '$x = F/k = 10/400 = 0.025$ m. $E = \\frac{1}{2}kx^2 = 0.125$ J.' },
  { cat: 'ayt-fen', sub: 'fizik', q: 'Ses dalgasının havada hızı 340 m/s, frekansı 170 Hz ise dalga boyu kaç m\'dir?', o: ['A) 0.5', 'B) 1', 'C) 2', 'D) 3', 'E) 5'], c: 2, e: '$\\lambda = v/f = 340/170 = 2$ m.' },
  { cat: 'ayt-fen', sub: 'fizik', q: '2 kg cisim 10 m/s hızla 3 kg duran cisme çarpıp yapışıyor. Ortak hız kaç m/s?', o: ['A) 2', 'B) 4', 'C) 5', 'D) 6', 'E) 8'], c: 1, e: '$2 \\times 10 = (2+3)v\' \\implies v\' = 20/5 = 4$ m/s.' },
  { cat: 'ayt-fen', sub: 'fizik', q: 'İdeal transformatörde giriş 200 V, 2 A; çıkış 100 V ise çıkış akımı kaç A?', o: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'], c: 3, e: '$200 \\times 2 = 100 \\times I_s \\implies I_s = 4$ A.' },
  { cat: 'ayt-fen', sub: 'fizik', q: 'Basit sarkacın periyodu 2 s\'dir. Boy 4 katına çıkarsa yeni periyot kaç s?', o: ['A) 1', 'B) 2', 'C) 4', 'D) 6', 'E) 8'], c: 2, e: '$T \\propto \\sqrt{L}$, 4 katına çıkarsa $T\' = 2T = 4$ s.' },
  { cat: 'ayt-fen', sub: 'kimya', q: '$N_2 + 3H_2 \\to 2NH_3$ tepkimesinde 1 mol N₂ ve 3 mol H₂\'den kaç mol NH₃ oluşur?', o: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 5'], c: 1, e: 'Katsayılara göre 2 mol NH₃ oluşur.' },
  { cat: 'ayt-fen', sub: 'kimya', q: 'pH=3 olan çözeltinin pOH\'ı kaçtır?', o: ['A) 3', 'B) 5', 'C) 7', 'D) 9', 'E) 11'], c: 4, e: 'pH + pOH = 14 \\implies pOH = 11.' },
  { cat: 'ayt-fen', sub: 'kimya', q: '$^{235}_{92}U$ atomunda kaç nötron vardır?', o: ['A) 92', 'B) 143', 'C) 235', 'D) 327', 'E) 92-235 arası'], c: 1, e: 'Nötron = 235 - 92 = 143.' },
  { cat: 'ayt-fen', sub: 'kimya', q: 'Aşağıdakilerden hangisi aromatik hidrokarbondur?', o: ['A) CH₄', 'B) C₂H₆', 'C) C₆H₆', 'D) C₂H₂', 'E) C₄H₁₀'], c: 2, e: 'Benzen (C₆H₆) aromatik hidrokarbondur.' },
  { cat: 'ayt-fen', sub: 'biyoloji', q: 'Profaz evresinde aşağıdakilerden hangisi gerçekleşir?', o: ['A) Kromozomlar ekvatora dizilir', 'B) Kromatin iplikler kromozom olur', 'C) Kardeş kromatitler ayrılır', 'D) Sitoplazma bölünür', 'E) DNA replike olur'], c: 1, e: 'Profazda kromatin iplikler kısalıp kalınlaşarak kromozom haline gelir.' },
  { cat: 'ayt-fen', sub: 'biyoloji', q: 'Aşağıdakilerden hangisi prokaryot hücre yapısına sahiptir?', o: ['A) Amip', 'B) Maya', 'C) Bakteri', 'D) Bitki', 'E) Hayvan'], c: 2, e: 'Bakteriler prokaryot, diğerleri ökaryot hücrelidir.' },
  { cat: 'ayt-fen', sub: 'biyoloji', q: 'Kan şekeri düştüğünde kana glikoz salgılanmasını sağlayan hormon hangisidir?', o: ['A) İnsülin', 'B) Glukagon', 'C) Tiroksin', 'D) Kortizol', 'E) Adrenalin'], c: 1, e: 'Glukagon, karaciğerde glikojenin glikoza dönüşümünü uyarır.' },
  { cat: 'ayt-fen', sub: 'biyoloji', q: 'Mayoz bölünme sonucu kaç hücre oluşur?', o: ['A) 1', 'B) 2', 'C) 3', 'D) 4', 'E) 6'], c: 3, e: 'Mayoz sonucu 4 haploid hücre oluşur.' },
  // ---- AYT EDEBİYAT-SOS1 (12 soru) ----
  { cat: 'ayt-edebiyat-sos1', sub: 'edebiyat', q: 'Aşağıdakilerden hangisi Tanzimat Edebiyatı sanatçılarından biri değildir?', o: ['A) Şinasi', 'B) Namık Kemal', 'C) Ziya Paşa', 'D) Ahmet Hamdi Tanpınar', 'E) Recaizade Mahmut Ekrem'], c: 3, e: 'Ahmet Hamdi Tanpınar, Cumhuriyet dönemi yazarıdır.' },
  { cat: 'ayt-edebiyat-sos1', sub: 'edebiyat', q: '"Sana dar gelmeyecek makberi kimler kazsın? / Gömelim gel seni tarihe!" sözü hangi şaire aittir?', o: ['A) Mehmet Akif Ersoy', 'B) Yahya Kemal Beyatlı', 'C) Tevfik Fikret', 'D) Ziya Gökalp', 'E) Faruk Nafiz Çamlıbel'], c: 1, e: 'Yahya Kemal Beyatlı\'nın meşhur mısralarıdır.' },
  { cat: 'ayt-edebiyat-sos1', sub: 'edebiyat', q: 'Türk edebiyatında ilk yerli roman aşağıdakilerden hangisidir?', o: ['A) İntibah', 'B) Taaşşuk-ı Talat ve Fitnat', 'C) Araba Sevdası', 'D) Sergüzeşt', 'E) Cezmi'], c: 1, e: 'Şemsettin Sami\'nin Taaşşuk-ı Talat ve Fitnat\'ı ilk yerli romandır.' },
  { cat: 'ayt-edebiyat-sos1', sub: 'edebiyat', q: 'Aşağıdaki eserlerden hangisi Hüseyin Nihal Atsız\'a aittir?', o: ['A) Safahat', 'B) Bozkurtlar', 'C) Çalıkuşu', 'D) Yaban', 'E) Sinekli Bakkal'], c: 1, e: 'Bozkurtlar, Hüseyin Nihal Atsız\'ın romanıdır.' },
  { cat: 'ayt-edebiyat-sos1', sub: 'tarih1', q: 'Malazgirt Meydan Muharebesi hangi yıl yapılmıştır?', o: ['A) 1048', 'B) 1071', 'C) 1075', 'D) 1085', 'E) 1099'], c: 1, e: 'Malazgirt Savaşı, 1071 yılında yapılmıştır.' },
  { cat: 'ayt-edebiyat-sos1', sub: 'tarih1', q: 'İstanbul\'un fethi hangi padişah döneminde gerçekleşmiştir?', o: ['A) II. Murad', 'B) Fatih Sultan Mehmed', 'C) Yavuz Sultan Selim', 'D) Kanuni Sultan Süleyman', 'E) II. Bayezid'], c: 1, e: 'İstanbul, Fatih Sultan Mehmed tarafından 1453\'te fethedilmiştir.' },
  { cat: 'ayt-edebiyat-sos1', sub: 'cografya1', q: 'Türkiye\'de en fazla yağış alan bölge aşağıdakilerden hangisidir?', o: ['A) Akdeniz', 'B) Karadeniz', 'C) Marmara', 'D) Ege', 'E) Doğu Anadolu'], c: 1, e: 'Karadeniz Bölgesi, her mevsim yağış alarak en fazla yağışı alan bölgedir.' },
  { cat: 'ayt-edebiyat-sos1', sub: 'cografya1', q: 'Aşağıdaki yerlerden hangisi Türkiye\'de nüfus yoğunluğu en az olan bölgelerdendir?', o: ['A) İstanbul', 'B) İzmir', 'C) Tunceli', 'D) Ankara', 'E) Bursa'], c: 2, e: 'Tunceli, dağlık ve engebeli arazi yapısı nedeniyle nüfus yoğunluğu düşük illerdendir.' },
  // ---- AYT SOS2 (12 soru) ----
  { cat: 'ayt-sos2', sub: 'tarih2', q: 'Osmanlı Devleti\'nde ilk defa medrese açan padişah aşağıdakilerden hangisidir?', o: ['A) Osman Gazi', 'B) Orhan Gazi', 'C) I. Murad', 'D) Yıldırım Bayezid', 'E) II. Mehmed'], c: 1, e: 'Orhan Gazi, İznik\'te ilk medreseyi açtırmıştır.' },
  { cat: 'ayt-sos2', sub: 'tarih2', q: 'Türkiye Cumhuriyeti\'nin ilk anayasası aşağıdakilerden hangisidir?', o: ['A) 1876 Kanun-i Esasi', 'B) 1921 Teşkilat-ı Esasiye', 'C) 1924 Anayasası', 'D) 1961 Anayasası', 'E) 1982 Anayasası'], c: 1, e: '1921 Teşkilat-ı Esasiye, Cumhuriyet\'in ilk anayasasıdır.' },
  { cat: 'ayt-sos2', sub: 'cografya2', q: 'Haritalarda yükselti ve çukur alanları göstermek için kullanılan yöntem aşağıdakilerden hangisidir?', o: ['A) Tarama', 'B) İzohips', 'C) Renklendirme', 'D) Noktalama', 'E) Kabartma'], c: 1, e: 'İzohips (eş yükselti) eğrileri, yükseltileri göstermede kullanılır.' },
  { cat: 'ayt-sos2', sub: 'cografya2', q: 'Türkiye\'nin en büyük gölü aşağıdakilerden hangisidir?', o: ['A) İznik Gölü', 'B) Beyşehir Gölü', 'C) Van Gölü', 'D) Tuz Gölü', 'E) Sapanca Gölü'], c: 2, e: 'Van Gölü, 3.713 km² yüzölçümüyle Türkiye\'nin en büyük gölüdür.' },
  { cat: 'ayt-sos2', sub: 'felsefe', q: '"Bilgi, duyumlardan gelir; zihinde doğuştan hiçbir bilgi yoktur." görüşü aşağıdakilerden hangisine aittir?', o: ['A) Rasyonalizm', 'B) Empirizm', 'C) Kritisizm', 'D) Entüisyonizm', 'E) Pozitivizm'], c: 1, e: 'Empirizm (deneycilik), tüm bilginin deneyimden geldiğini savunur. Locke ve Hume temsilcileridir.' },
  { cat: 'ayt-sos2', sub: 'felsefe', q: '"Kategorik imperatif" (koşulsuz buyruk) kavramı hangi filozofa aittir?', o: ['A) Sokrates', 'B) Platon', 'C) Kant', 'D) Hegel', 'E) Nietzsche'], c: 2, e: 'Kant\'ın ahlak felsefesinde kategorik imperatif, koşulsuz olarak uyulması gereken ahlak yasasıdır.' },
  { cat: 'ayt-sos2', sub: 'din', q: 'İslam\'da ilk farz kılınan ibadet aşağıdakilerden hangisidir?', o: ['A) Oruç', 'B) Namaz', 'C) Zekât', 'D) Hac', 'E) Kelime-i şehadet'], c: 4, e: 'Kelime-i şehadet getirmek, İslam\'ın ilk şartı ve ilk farz olan ibadettir.' },
  { cat: 'ayt-sos2', sub: 'din', q: 'Kur\'an-ı Kerim\'de adı geçen ve Hz. İbrahim\'in oğlu olan peygamber aşağıdakilerden hangisidir?', o: ['A) Hz. Musa', 'B) Hz. İsmail', 'C) Hz. Davud', 'D) Hz. Süleyman', 'E) Hz. Yunus'], c: 1, e: 'Hz. İsmail, Hz. İbrahim\'in oğludur ve Kâbe\'nin inşasında babasına yardım etmiştir.' },
];

for (const q of questions) {
  await sql`INSERT INTO questions (category_id, sub_category, question, options, correct_answer, explanation) VALUES (${q.cat}, ${q.sub}, ${q.q}, ${JSON.stringify(q.o)}, ${q.c}, ${q.e})`;
}
console.log(`AYT seed: ${questions.length} questions inserted`);
