import { neon } from '@neondatabase/serverless';
const sql = neon(process.env.DATABASE_URL);

const questions = [
  // ---- TYT TÜRKÇE (20 soru) ----
  { cat: 'tyt-turkce', sub: 'sozcuk-anlami', q: '"Bu roman, yazarın en olgun dönem ürünüdür." cümlesindeki "ürün" sözcüğünün cümleye kattığı anlam aşağıdakilerden hangisidir?', o: ['A) Eser', 'B) Kazanç', 'C) Ticari mal', 'D) Servet', 'E) Getiri'], c: 0, e: '"Ürün" sözcüğü bu cümlede "eser, yapıt" anlamında kullanılmıştır.' },
  { cat: 'tyt-turkce', sub: 'sozcuk-anlami', q: 'Aşağıdaki cümlelerin hangisinde "derin" sözcüğü mecaz anlamda kullanılmıştır?', o: ['A) Kuyunun derinliği on metreyi buluyor.', 'B) Derin bir nefes alıp konuşmaya başladı.', 'C) Bu konuda derin bir bilgiye sahip değilim.', 'D) Denizin bu bölümü oldukça derin.', 'E) Yaranın derinliği doktoru endişelendirdi.'], c: 2, e: '"Derin" sözcüğü C seçeneğinde "yoğun, kapsamlı" anlamında mecaz olarak kullanılmıştır.' },
  { cat: 'tyt-turkce', sub: 'cumle-anlami', q: 'Aşağıdaki cümlelerin hangisinde "amaç-sonuç" ilişkisi vardır?', o: ['A) Yağmur yağdığı için maç ertelendi.', 'B) Sınava iyi hazırlanmak için çok çalıştı.', 'C) Arabayı yıkadı ama hava tekrar bulutlandı.', 'D) Ödevini bitirince arkadaşlarıyla oynadı.', 'E) Araba kullanmayı öğrendi ancak ehliyet almadı.'], c: 1, e: 'B seçeneğinde "için" edatı amaç bildirmektedir.' },
  { cat: 'tyt-turkce', sub: 'cumle-anlami', q: '"Bu roman, sadece gençlerin değil yetişkinlerin de ilgisini çekebilecek bir eser." cümlesindeki anlam ilişkisi aşağıdakilerden hangisidir?', o: ['A) Karşılaştırma', 'B) Koşul', 'C) Neden-sonuç', 'D) Amaç-sonuç', 'E) Varsayım'], c: 0, e: 'Gençler ve yetişkinler karşılaştırılmaktadır.' },
  { cat: 'tyt-turkce', sub: 'paragraf', q: 'Sanat, insanın kendini ifade etme biçimlerinden yalnızca biridir. Ancak diğer ifade biçimlerinden farklı olarak sanat, evrensel bir dil kullanır. Bir resim, bir heykel ya da bir müzik eseri, hangi kültürden olursa olsun her insana aynı duyguyu yaşatabilir. Bu yönüyle sanat, insanlığın ortak mirasıdır ve kültürler arası iletişimin en güçlü aracıdır. Bu parçada asıl anlatılmak istenen aşağıdakilerden hangisidir?', o: ['A) Sanat, kültürden kültüre değişen bir olgudur.', 'B) Her insan aynı sanat eserinden farklı duygular hisseder.', 'C) Sanatın en önemli özelliği evrensel olmasıdır.', 'D) Sanat eserleri yalnızca belirli bir kitleye hitap eder.', 'E) Kültürler arası iletişimde dil en önemli araçtır.'], c: 2, e: 'Parçada sanatın evrensel bir dil kullandığı ve insanlığın ortak mirası olduğu vurgulanmaktadır.' },
  { cat: 'tyt-turkce', sub: 'paragraf', q: 'Günümüzde bilgiye ulaşmak hiç olmadığı kadar kolay. Ancak asıl mesele, bu bilgi yığını içinden doğru olanı seçebilmek. İnternette her gün milyonlarca yeni içerik yayımlanıyor. Bunların bir kısmı doğru ve güvenilirken, bir kısmı yanıltıcı ve manipülatif olabiliyor. Bu nedenle bilgi okuryazarlığı, 21. yüzyılın en önemli becerilerinden biri haline gelmiştir. Bu parçaya göre, bilgi okuryazarlığının önemi neye dayandırılmaktadır?', o: ['A) Bilginin herkes tarafından üretilebilmesine', 'B) İnternetin daha fazla kullanılmasına', 'C) Doğru bilgi ile yanlış bilginin bir arada bulunmasına', 'D) Bilginin güncellenme hızının artmasına', 'E) İnsanların bilgiye ücretsiz erişebilmesine'], c: 2, e: 'Doğru ve yanlış bilginin bir arada bulunması bilgi okuryazarlığını önemli hale getirmiştir.' },
  { cat: 'tyt-turkce', sub: 'paragraf', q: '(I) Edebiyat, toplumun bir aynasıdır. (II) Her dönemin edebiyatı, o dönemin sosyal ve kültürel özelliklerini yansıtır. (III) Bu nedenle bir dönemi anlamak için o dönemin edebi eserlerini incelemek yeterlidir. (IV) Ancak edebiyat, toplumu yalnızca yansıtmakla kalmaz, onu şekillendirir. (V) Toplumsal değişimlerin öncüsü olan yazarlar, eserleriyle kitleleri etkilemiştir. Bu parçadaki numaralanmış cümlelerden hangisi düşüncenin akışını bozmaktadır?', o: ['A) I', 'B) II', 'C) III', 'D) IV', 'E) V'], c: 2, e: 'III. cümledeki "yeterlidir" ifadesi kesin ve abartılı bir yargıdır, parçanın genel akışına uymaz.' },
  { cat: 'tyt-turkce', sub: 'dil-bilgisi', q: 'Aşağıdaki cümlelerin hangisinde yazım yanlışı vardır?', o: ['A) Yarınki toplantıya katılacak mısın?', 'B) Her şey yolunda gidiyordu ki bir anda herşey değişti.', 'C) Hiçbir şey eskisi gibi olmayacak.', 'D) Arkadaşım da bizimle gelecekmiş.', 'E) Önümüzdeki hafta İzmir\'e gidiyoruz.'], c: 1, e: '"Her şey" ayrı yazılır. B seçeneğindeki "herşey" yanlış yazılmıştır.' },
  { cat: 'tyt-turkce', sub: 'dil-bilgisi', q: 'Aşağıdaki cümlelerin hangisinde noktalama yanlışı vardır?', o: ['A) Ali, Ayşe ve Mehmet sinemaya gittiler.', 'B) Ankara\'ya; İstanbul\'a ve İzmir\'e gidecek.', 'C) Peki, sen ne düşünüyorsun?', 'D) Kitabı okudum ama hiçbir şey anlamadım.', 'E) Yaşlı adam: "Merhaba evlat!" dedi.'], c: 1, e: 'Sıralı cümlelerde noktalı virgül değil virgül kullanılmalıdır.' },
  { cat: 'tyt-turkce', sub: 'paragraf', q: 'Bir dilin zenginliği, o dilin sözcük sayısıyla değil, anlatım olanaklarıyla ölçülür. Türkçe, bu açıdan son derece zengin bir dildir. Deyimler, atasözleri ve mecazlı anlatımlar sayesinde aynı düşünceyi pek çok farklı biçimde ifade edebiliriz. Bu parçada Türkçenin hangi özelliği vurgulanmaktadır?', o: ['A) Sözcük sayısının fazla olması', 'B) Tarihsel kökeninin eski olması', 'C) Anlatım gücünün yüksek olması', 'D) Yabancı dillerden etkilenmesi', 'E) Dil bilgisi kurallarının karmaşık olması'], c: 2, e: 'Türkçenin anlatım gücünün yüksek olduğu vurgulanmıştır.' },
  { cat: 'tyt-turkce', sub: 'paragraf', q: 'Şehir hayatı, insanlara birçok kolaylık sunuyor olsa da beraberinde sorunlar da getirmektedir. Bunların başında, doğal çevreden uzaklaşma ve sürekli bir koşturma içinde olma hali geliyor. Oysa insan, doğayla iç içe olduğunda kendini daha huzurlu hissetmektedir. Bu parçadan aşağıdakilerden hangisi çıkarılamaz?', o: ['A) Şehir hayatının zorlukları vardır.', 'B) İnsanlar doğal ortamlarda daha huzurlu olur.', 'C) Şehirler her geçen gün daha kalabalıklaşmaktadır.', 'D) Şehir hayatı bazı kolaylıklar sağlamaktadır.', 'E) Doğadan uzaklaşmak şehir hayatının bir sonucudur.'], c: 2, e: 'Parçada şehirlerin kalabalıklaşmasından söz edilmemektedir.' },
  // ---- TYT SOSYAL (12 soru) ----
  { cat: 'tyt-sosyal', sub: 'tarih', q: 'Osmanlı Devleti\'nde, fethedilen topraklardaki yerli halkın can, mal, ırz ve din güvenliğini garanti altına alan belge aşağıdakilerden hangisidir?', o: ['A) Ferman', 'B) Berat', 'C) Ahidname', 'D) Kanunname', 'E) Vakfiye'], c: 2, e: 'Ahidname, Osmanlı\'nın fethettiği bölgelerdeki halka verdiği güvence belgesidir.' },
  { cat: 'tyt-sosyal', sub: 'tarih', q: 'Kurtuluş Savaşı\'nda düzenli ordunun Batı Cephesi\'ndeki ilk askerî başarısı aşağıdakilerden hangisidir?', o: ['A) Sakarya Meydan Muharebesi', 'B) I. İnönü Muharebesi', 'C) II. İnönü Muharebesi', 'D) Büyük Taarruz', 'E) Kütahya-Eskişehir Savaşı'], c: 1, e: 'I. İnönü Muharebesi, düzenli ordunun ilk zaferidir.' },
  { cat: 'tyt-sosyal', sub: 'cografya', q: 'Türkiye\'de aşağıdaki bölgelerden hangisinde kış sıcaklık ortalamaları diğerlerine göre daha yüksektir?', o: ['A) İç Anadolu', 'B) Doğu Anadolu', 'C) Akdeniz', 'D) Karadeniz', 'E) Güneydoğu Anadolu'], c: 2, e: 'Akdeniz Bölgesi, enlem ve denizellik etkisiyle kışın en ılık bölgedir.' },
  { cat: 'tyt-sosyal', sub: 'cografya', q: 'Harita ölçeği 1/500.000 olan bir haritada 5 cm olarak gösterilen iki şehir arası gerçek uzaklık kaç km\'dir?', o: ['A) 10', 'B) 15', 'C) 20', 'D) 25', 'E) 50'], c: 3, e: 'GU = 5 × 500.000 = 2.500.000 cm = 25 km.' },
  { cat: 'tyt-sosyal', sub: 'felsefe', q: '"Düşünüyorum, öyleyse varım." sözüyle bilinen filozof aşağıdakilerden hangisidir?', o: ['A) Platon', 'B) Aristoteles', 'C) Descartes', 'D) Kant', 'E) Nietzsche'], c: 2, e: 'Descartes, modern felsefenin kurucusudur.' },
  { cat: 'tyt-sosyal', sub: 'felsefe', q: 'Varlığın temelini maddeye dayandıran felsefi akım aşağıdakilerden hangisidir?', o: ['A) İdealizm', 'B) Materyalizm', 'C) Dualizm', 'D) Entüisyonizm', 'E) Pragmatizm'], c: 1, e: 'Materyalizm, her şeyin maddeden oluştuğunu savunur.' },
  { cat: 'tyt-sosyal', sub: 'din', q: 'İslam dininin temel kaynakları aşağıdakilerden hangisidir?', o: ['A) Kur\'an-ı Kerim ve Sünnet', 'B) Kur\'an-ı Kerim ve Tevrat', 'C) İncil ve Sünnet', 'D) Tevrat ve İncil', 'E) Yalnızca Kur\'an-ı Kerim'], c: 0, e: 'Kur\'an-ı Kerim ve Hz. Muhammed\'in sünneti İslam\'ın iki temel kaynağıdır.' },
  { cat: 'tyt-sosyal', sub: 'din', q: 'Aşağıdakilerden hangisi İslam\'ın inanç esaslarından biri değildir?', o: ['A) Allah\'a inanmak', 'B) Meleklere inanmak', 'C) Oruç tutmak', 'D) Peygamberlere inanmak', 'E) Ahiret gününe inanmak'], c: 2, e: 'Oruç, imanın şartı değil İslam\'ın şartıdır.' },
  // ---- TYT MATEMATİK (16 soru) ----
  { cat: 'tyt-matematik', sub: 'matematik', q: 'Bir otobüsteki yolcuların $\\frac{3}{5}$\'i erkektir. Otobüse 10 erkek daha binince erkekler tüm yolcuların $\\frac{2}{3}$\'si oluyor. Başlangıçta kaç yolcu vardır?', o: ['A) 30', 'B) 40', 'C) 45', 'D) 50', 'E) 60'], c: 3, e: 'x yolcu olsun. $\\frac{3x}{5} + 10 = \\frac{2}{3}(x+10)$. $9x + 150 = 10x + 100 \\implies x = 50$.' },
  { cat: 'tyt-matematik', sub: 'matematik', q: '$|2x - 6| < 4$ eşitsizliğinin çözüm kümesi aşağıdakilerden hangisidir?', o: ['A) (1, 5)', 'B) [1,5]', 'C) (1, 6)', 'D) (2, 5)', 'E) (-1, 5)'], c: 0, e: '$-4 < 2x - 6 < 4 \\implies 2 < 2x < 10 \\implies 1 < x < 5$.' },
  { cat: 'tyt-matematik', sub: 'matematik', q: 'Bir torbada 3 kırmızı, 4 mavi, 5 beyaz top vardır. Rastgele çekilen topun kırmızı veya mavi olma olasılığı kaçtır?', o: ['A) $\\frac{1}{4}$', 'B) $\\frac{7}{12}$', 'C) $\\frac{1}{3}$', 'D) $\\frac{5}{12}$', 'E) $\\frac{3}{4}$'], c: 1, e: 'Toplam 12 top. İstenen: 3+4=7. Olasılık: $\\frac{7}{12}$.' },
  { cat: 'tyt-matematik', sub: 'matematik', q: '$f(x) = 3x - 2$ ve $g(x) = x + 4$ ise $(f \\circ g)(x)$ aşağıdakilerden hangisidir?', o: ['A) $3x + 10$', 'B) $3x + 12$', 'C) $3x + 2$', 'D) $3x - 14$', 'E) $x + 2$'], c: 0, e: '$f(g(x)) = 3(x+4) - 2 = 3x + 12 - 2 = 3x + 10$.' },
  { cat: 'tyt-matematik', sub: 'matematik', q: '$\\sqrt{128} + \\sqrt{50} - \\sqrt{18}$ işleminin sonucu kaçtır?', o: ['A) $5\\sqrt{2}$', 'B) $8\\sqrt{2}$', 'C) $10\\sqrt{2}$', 'D) $12\\sqrt{2}$', 'E) $15\\sqrt{2}$'], c: 1, e: '$8\\sqrt{2} + 5\\sqrt{2} - 3\\sqrt{2} = 10\\sqrt{2}$.' },
  { cat: 'tyt-matematik', sub: 'matematik', q: 'Ortalaması 24 olan 6 sayıya hangi sayı eklenirse yeni ortalama 25 olur?', o: ['A) 28', 'B) 29', 'C) 30', 'D) 31', 'E) 32'], c: 3, e: '144 + x = 175 \\implies x = 31.' },
  { cat: 'tyt-matematik', sub: 'geometri', q: 'Bir üçgenin iç açıları 2, 3 ve 5 ile orantılıdır. En büyük açı kaç derecedir?', o: ['A) 54', 'B) 72', 'C) 90', 'D) 108', 'E) 126'], c: 2, e: '$2k+3k+5k=180 \\implies k=18$. En büyük: $5 \\times 18 = 90$.' },
  { cat: 'tyt-matematik', sub: 'geometri', q: 'Yarıçapı 6 cm olan dairenin alanı kaç $\\pi$ cm²\'dir?', o: ['A) 6', 'B) 12', 'C) 18', 'D) 24', 'E) 36'], c: 4, e: '$\\pi r^2 = \\pi \\times 36 = 36\\pi$ cm².' },
  { cat: 'tyt-matematik', sub: 'geometri', q: 'Dikdörtgende $|AB|=12$, $|BC|=5$ ise $|AC|$ köşegeni kaç cm\'dir?', o: ['A) 10', 'B) 11', 'C) 12', 'D) 13', 'E) 14'], c: 3, e: '$\\sqrt{12^2 + 5^2} = \\sqrt{144+25} = \\sqrt{169} = 13$.' },
  { cat: 'tyt-matematik', sub: 'geometri', q: 'Düzgün altıgenin bir iç açısı kaç derecedir?', o: ['A) 60', 'B) 90', 'C) 108', 'D) 120', 'E) 135'], c: 3, e: '$\\frac{(n-2) \\times 180}{n} = \\frac{4 \\times 180}{6} = 120$.' },
  // ---- TYT FEN (12 soru) ----
  { cat: 'tyt-fen', sub: 'fizik', q: '5 kg kütleli cisme 20 N kuvvet uygulanırsa ivmesi kaç m/s² olur? (Sürtünmesiz)', o: ['A) 2', 'B) 4', 'C) 5', 'D) 10', 'E) 20'], c: 1, e: '$a = F/m = 20/5 = 4$ m/s².' },
  { cat: 'tyt-fen', sub: 'fizik', q: '6 ohm\'luk iletkenden 2 A akım geçerse uçlar arası potansiyel farkı kaç volttur?', o: ['A) 3', 'B) 6', 'C) 8', 'D) 10', 'E) 12'], c: 4, e: '$V = IR = 2 \\times 6 = 12$ V.' },
  { cat: 'tyt-fen', sub: 'fizik', q: '2 kg kütleli cisim 3 m/s hızla hareket ediyorsa kinetik enerjisi kaç joule\'dür?', o: ['A) 3', 'B) 6', 'C) 9', 'D) 12', 'E) 18'], c: 2, e: '$E_k = \\frac{1}{2}mv^2 = \\frac{1}{2} \\times 2 \\times 9 = 9$ J.' },
  { cat: 'tyt-fen', sub: 'fizik', q: 'Serbest bırakılan cisim 4 saniyede yere düşüyor. Yükseklik kaç metredir? (g=10)', o: ['A) 40', 'B) 60', 'C) 80', 'D) 100', 'E) 120'], c: 2, e: '$h = \\frac{1}{2}gt^2 = 5 \\times 16 = 80$ m.' },
  { cat: 'tyt-fen', sub: 'kimya', q: 'Mavi turnusolu kırmızıya çeviren X, Zn ile H₂ çıkaran Y, pH=11 olan Z. X, Y, Z nedir?', o: ['A) X:Asit, Y:Asit, Z:Baz', 'B) X:Baz, Y:Asit, Z:Asit', 'C) X:Asit, Y:Baz, Z:Baz', 'D) X:Baz, Y:Baz, Z:Asit', 'E) X:Asit, Y:Asit, Z:Asit'], c: 0, e: 'X asit (turnusol), Y asit (H₂ çıkışı), Z baz (pH>7).' },
  { cat: 'tyt-fen', sub: 'kimya', q: 'Periyodik cetvelde aynı grupta yukarıdan aşağı inildikçe hangisi artar?', o: ['A) İyonlaşma enerjisi', 'B) Elektronegatiflik', 'C) Atom yarıçapı', 'D) Elektron ilgisi', 'E) Değerlik elektron sayısı'], c: 2, e: 'Atom numarası arttıkça atom yarıçapı artar.' },
  { cat: 'tyt-fen', sub: 'kimya', q: 'Aşağıdakilerden hangisi kovalent bağlı bileşiktir?', o: ['A) NaCl', 'B) CaO', 'C) H₂O', 'D) KBr', 'E) MgO'], c: 2, e: 'H₂O, elektron ortaklaşması (kovalent bağ) ile oluşur.' },
  { cat: 'tyt-fen', sub: 'biyoloji', q: 'Canlıların en küçük yapı ve işlev birimi aşağıdakilerden hangisidir?', o: ['A) Doku', 'B) Organ', 'C) Sistem', 'D) Hücre', 'E) Organel'], c: 3, e: 'Hücre, canlılığın temel birimidir.' },
  { cat: 'tyt-fen', sub: 'biyoloji', q: 'Fotosentezin gerçekleştiği organel aşağıdakilerden hangisidir?', o: ['A) Mitokondri', 'B) Kloroplast', 'C) Ribozom', 'D) Golgi', 'E) ER'], c: 1, e: 'Kloroplast, klorofil içerir ve fotosentez yapar.' },
  { cat: 'tyt-fen', sub: 'biyoloji', q: 'Kanın pıhtılaşmasında görev alan hücreler aşağıdakilerden hangisidir?', o: ['A) Akyuvarlar', 'B) Alyuvarlar', 'C) Trombositler', 'D) Plazma hücreleri', 'E) Mast hücreleri'], c: 2, e: 'Trombositler (kan pulcukları) pıhtılaşmayı sağlar.' },
];

for (const q of questions) {
  await sql`INSERT INTO questions (category_id, sub_category, question, options, correct_answer, explanation) VALUES (${q.cat}, ${q.sub}, ${q.q}, ${JSON.stringify(q.o)}, ${q.c}, ${q.e})`;
}
console.log(`TYT seed: ${questions.length} questions inserted`);
